# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# - example yml
# https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
    - cp configs/default.example.toml book-teacher.toml
    - cp configs/teacher/default.example.json book-teacher.json
# https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/book/
    binary: book-teacher
    goos:
      - linux
      - windows
      - darwin
# https://goreleaser.com/customization/archive/
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - book-teacher.toml
      - book-teacher.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
      - '^images:'
      - '^scripts:'

# https://goreleaser.com/customization/homebrew/
brews:
  - tap:
      owner: hiromaily
      name: homebrew-tap
    folder: Formula
    description: find teacher's lesson
    homepage: https://github.com/hiromaily/go-book-teacher
    install: |
      bin.install "book-teacher"
      etc.install "book-teacher/book-teacher.toml"
      etc.install "book-teacher/book-teacher.json"
    test: |
      system "#{bin}/book-teacher -v"