language: go
sudo: false
go:
  - tip

services:
  - redis-server

env:
  global:
    - GO_PROJ_PATH='/home/travis/gopath/src/github.com/hiromaily/go-book-teacher/cmd/book/'

before_install:
  - go get github.com/tools/godep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go fmt ./...
  - go vet $(go list ./... | grep -v /vendor/)
  - cd ${GO_PROJ_PATH};go test -v -covermode=count -coverprofile=profile.cov -t ../../data/toml/slackon.toml
  - cd ${GO_PROJ_PATH};goveralls -coverprofile=profile.cov -service=travis-ci

branches:
  only:
    - master
