version: '3.9'

volumes:
  rdb: {}

services:
  # redis
  redis:
    image: redis:6.0.10-alpine3.12
    container_name: book-redis
    ports:
      - "6379"
    volumes:
      - rdb:/data
    restart: always
    command: redis-server --requirepass password --appendonly yes

  # golang:go-book-teacher
  book:
    build:
      context: ./build/docker/
      dockerfile: Dockerfile
      args:
        redisHostName: redis-server
    image: go-book-teacher:v1.1
    container_name: book
    #env_file: ./build/docker/.env
    environment:
      ENC_KEY: ${ENC_KEY}
      ENC_IV: ${ENC_IV}
    links:
      - redis:redis-server
    depends_on:
      - redis
    stdin_open: true
    tty: true
    command: bash
