version: '3.9'

services:
  # Redis
  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # golang:go-book-teacher
  book:
    volumes:
      - ./:/go/src/github.com/hiromaily/go-book-teacher
    command: bash