environment = 0    #0:local, 1:docker, 2:heroku

status_file = "/tmp/status.log"

[redis]
encrypted = false
url = ""

[mail]
encrypted = false
mail_to = ""
mail_from = ""

[mail.smtp]
address = ""
pass = ""
server = ""
port = 587
