# local

[site]
type = "DMM"
url = "http://eikaiwa.dmm.com/"
concurrency = 20

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
# redis should be enabled on Heroku environment
[redis]
encrypted = true
url = "Scx3B/7qmzC6e0x0GWWxsmV4oUfNSFpOiZ8cVNM4DeSX4L2ebwwOfP2uBkKdWhxmC1XVUaF1xL/Mzk8xHklQ28jKy8k3/H5NOo6ZpWx8xPuqppzehaVFqoUcec8qYQq3"

[text]
path = "./status.log"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
# mail or slack should be enabled on Heroku environment
[slack]
encrypted = true
key = "HP/9upIf+CwLGuDj2V0xfqulICwv1nHhQXy+S2TSEhFzYfEnt9zzWjVtoMT/8Rb7"

[browser]
enabled = false

# mail or slack should be enabled on Heroku environment
[mail]
encrypted = false
mail_to = ""
mail_from = ""

[mail.smtp]
address = ""
pass = ""
server = ""
port = 587
