# heroku

interval = 0 # second :run every x second, run only once when interval is `0`

[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

[logger]
service = "book-teacher"
env = "custom" # dev, prod, custom :for only zap logger
level = "info" # debug, info, warn, error
is_stacktrace = false

# -----------------------------------------------------------------------------
# Save
# -----------------------------------------------------------------------------
[save]
mode = "redis"

[save.text]
path = "./status.log"

[save.redis]
# https://devcenter.heroku.com/articles/securing-heroku-redis
encrypted = false
url = ""
env = "REDIS_URL"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "slack"

[notification.console]
enabled = false

[notification.slack]
enabled = true
encrypted = true
key = "bPLOW06msIeCN0fPuvqP/1S58yozAMsNYwGfJ3F77Mw7xpz/revQufXGvj8iZExil3+j0wuhEhHlM+enVq70kU479UfVnPPepIezKQg80kEfUS3Bi/+5QLKkpHN1U7na65Le9niYPS/SU/aN/vdNUZb+lPvulvL/ZqudhLTsie8="

