# docker

[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
[storage]
mode = "redis"

[storage.text]
path = "/tmp/status.log"

[storage.redis]
encrypted = false
url = "redis://h:password@127.0.0.1:6379"


# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "cli"

[notification.cli]
enabled = true

[notification.slack]
enabled = false
encrypted = false
key = ""
