# for mail, but mail is not available

[site]
type = "DMM"
url = "http://eikaiwa.dmm.com/"
concurrency = 20

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
[redis]
encrypted = false
url = ""

[text]
path = "./status.log"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[slack]
encrypted = false
key = ""

[browser]
enabled = false

# mail should be enabled on Heroku environment
[mail]
encrypted = true
mail_to = "FcQjhb5ErsSBlh6EDwe69eLdcW/eJPKWtnTWmDPoAAM="
mail_from = "NnrrawdLR5gZ+YD0wtsIjwQf5UPBDVXDeej1GrYW8+E="

[mail.smtp]
address = "NnrrawdLR5gZ+YD0wtsIjwQf5UPBDVXDeej1GrYW8+E="
pass = "2kh28ukhCnQ6uCdlt9BK9tklGK21r7uZrEZSe1HqOx4="
server = "o4jKKaglwawhX58iGLqBvg=="
port = 587

