
interval = 60 # second :run every 60 second, run only once when interval is `0`

[logger]
service = "book-teacher"
env = "custom" # dev, prod, custom :for only zap logger
level = "debug" # debug, info, warn, error
is_stacktrace = true

[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
# redis should be enabled on Heroku environment
[redis]
encrypted = false
url = ""

[text]
path = "./status.log"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "slack"

[notification.console]
enabled = false

[notification.slack]
enabled = true
encrypted = true
key = "HP/9upIf+CwLGuDj2V0xfqulICwv1nHhQXy+S2TSEhFzYfEnt9zzWjVtoMT/8Rb7"
