[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
# redis should be enabled on Heroku environment
[redis]
encrypted = false
url = ""

[text]
path = "./status.log"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "slack"

[notification.cli]
enabled = false

[notification.slack]
enabled = true
encrypted = true
key = "HP/9upIf+CwLGuDj2V0xfqulICwv1nHhQXy+S2TSEhFzYfEnt9zzWjVtoMT/8Rb7"
