
interval = 60 # second :run every 60 second, run only once when interval is `0`

[logger]
service = "book-teacher"
env = "custom" # dev, prod, custom :for only zap logger
level = "debug" # debug, info, warn, error
is_stacktrace = true

[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
[storage]
mode = "text"

[storage.text]
path = "./status.log"

[storage.redis]
encrypted = false
url = ""


# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "console"

[notification.console]
enabled = true

[notification.slack]
enabled = false
encrypted = false
key = ""
