[site]
type = "dmm"
url = "http://eikaiwa.dmm.com/"

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
[storage]
mode = "text"

[storage.text]
path = "./status.log"

[storage.redis]
encrypted = false
url = ""


# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[notification]
mode = "cli"

[notification.cli]
enabled = true

[notification.slack]
enabled = false
encrypted = false
key = ""
