[site]
type = "DMM"
url = "http://eikaiwa.dmm.com/"
concurrency = 20

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
# redis should be enabled on Heroku environment
[redis]
encrypted = false
url = ""

[text]
path = "./status.log"

# -----------------------------------------------------------------------------
# Notification
# -----------------------------------------------------------------------------
[slack]
encrypted = true
key = "HP/9upIf+CwLGuDj2V0xfqulICwv1nHhQXy+S2TSEhFzYfEnt9zzWjVtoMT/8Rb7"

[browser]
enabled = false

# mail or slack should be enabled on Heroku environment
[mail]
encrypted = false
mail_to = ""
mail_from = ""

[mail.smtp]
address = ""
pass = ""
server = ""
port = 587
